steps:
  - label: "🧹 Lint & Checkstyle"
    command: |
        cp gradle.properties-example gradle.properties
        ./gradlew lint checkstyle
    plugins:
      - docker#v3.8.0:
          image: "wordpressmobile/android-build-image"
          environment:
            - "CI=true"

