common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Lint & Checkstyle"
    key: "lint_and_checkstyle"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew lint checkstyle
    artifact_paths:
      - "**/build/reports/lint-results.*"
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "Test"
    key: "test"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew test

  - label: "Build and upload to S3"
    depends_on:
      - "lint_and_checkstyle"
      - "test"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew \
          :WordPressUtils:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :WordPressUtils:publish
